# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/fajita/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),fajita)

$(call add-radio-file,radio/LOGO.img)
$(call add-radio-file,radio/abl.img)
$(call add-radio-file,radio/aop.img)
$(call add-radio-file,radio/bluetooth.img)
$(call add-radio-file,radio/cmnlib.img)
$(call add-radio-file,radio/cmnlib64.img)
$(call add-radio-file,radio/devcfg.img)
$(call add-radio-file,radio/dsp.img)
$(call add-radio-file,radio/fw_4j1ed.img)
$(call add-radio-file,radio/fw_4u1ea.img)
$(call add-radio-file,radio/hyp.img)
$(call add-radio-file,radio/keymaster.img)
$(call add-radio-file,radio/modem.img)
$(call add-radio-file,radio/qupfw.img)
$(call add-radio-file,radio/storsec.img)
$(call add-radio-file,radio/tz.img)
$(call add-radio-file,radio/xbl.img)
$(call add-radio-file,radio/xbl_config.img)

endif
