# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/fajita/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),fajita)

$(call add-radio-file-sha1-checked,radio/LOGO.img,eb2c7bb19991cd2e3b7330edc66e36bf9a3d94d1)
$(call add-radio-file-sha1-checked,radio/abl.img,fac1709d87c01f5628ab1f6a25ad302093648e70)
$(call add-radio-file-sha1-checked,radio/aop.img,dec4e10783e9cc8412b7c2cdc7df5c398753a131)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,cceca9193d8466c6709987fb3f1ad075b1379148)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,a07860185266fdd5e6292404738f7e3f51ee8f49)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,5da0762d3ff36a005da8f0a9143ce2c363187965)
$(call add-radio-file-sha1-checked,radio/devcfg.img,01191130726ad25dafff047b5a4e33f76ea11fc5)
$(call add-radio-file-sha1-checked,radio/dsp.img,2c2c031af161b86ab17938edc817987579bb5013)
$(call add-radio-file-sha1-checked,radio/fw_4j1ed.img,a81acbfb24d1857a5e26a99b10f84e5d5029ba49)
$(call add-radio-file-sha1-checked,radio/fw_4u1ea.img,fe245ca416ff8617abafb95ff9112d97af0a59b6)
$(call add-radio-file-sha1-checked,radio/hyp.img,1634f6e02caa92e6fac4e98c2ce85d43c1249950)
$(call add-radio-file-sha1-checked,radio/keymaster.img,59e27fd636ccc5038b0a7162dc4a268b790f49d0)
$(call add-radio-file-sha1-checked,radio/modem.img,b4bf6222778a7861d98b849ab3d471e47219fa42)
$(call add-radio-file-sha1-checked,radio/qupfw.img,7d5e34d36db1ca3675ff891b8fca2f017224c524)
$(call add-radio-file-sha1-checked,radio/storsec.img,356eb75b2d9742e139dbded7fba799ca20c9f4be)
$(call add-radio-file-sha1-checked,radio/tz.img,dd85ecddf6782640b361bb0f60def7e13755c645)
$(call add-radio-file-sha1-checked,radio/xbl.img,0e9e2c0d40a8a26432662a0c9c5407d75841409d)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,0c99f7f04727a940b7d4b4b66927219030c3e625)

endif
