# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/fajita/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    LOGO \
    abl \
    aop \
    bluetooth \
    cmnlib \
    cmnlib64 \
    devcfg \
    dsp \
    fw_4j1ed \
    fw_4u1ea \
    hyp \
    keymaster \
    modem \
    qupfw \
    storsec \
    tz \
    xbl \
    xbl_config
